all:
  vars:
    ansible_user: henrik

  children:

    demo_nodes:
      hosts:
        demo-k3s-01:
          ansible_host: 10.4.10.200
        demo-k3s-02:
          ansible_host: 10.4.10.201
        demo-k3s-03:
          ansible_host: 10.4.10.202
