all:
  vars:
    ansible_user: henrik

  children:

    students:
      hosts:
        DEMO-STUDENT01:
          ansible_host: 10.4.10.200
          demo_role: student
          demo_pair: 1
        DEMO-STUDENT02:
          ansible_host: 10.4.10.202
          demo_role: student
          demo_pair: 2
        DEMO-STUDENT03:
          ansible_host: 10.4.10.204
          demo_role: student
          demo_pair: 3

    targets:
      hosts:
        DEMO-TARGET01:
          ansible_host: 10.4.10.201
          demo_role: target
          demo_pair: 1
        DEMO-TARGET02:
          ansible_host: 10.4.10.203
          demo_role: target
          demo_pair: 2
        DEMO-TARGET03:
          ansible_host: 10.4.10.205
          demo_role: target
          demo_pair: 3
