name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [docker]

    steps:
      - name: Show environment
        run: |
          whoami
          hostname
          pwd

      - name: Test SSH to automation01
        run: |
          ssh \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -o ConnectTimeout=10 \
            henrik@10.4.10.50 \
            hostname
