---
- name: Install Prometheus Node Exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present
    update_cache: true

- name: Enable Prometheus Node Exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    enabled: true
    state: started
