all:
  children:
    automation:
      hosts:
        automation01:
          ansible_connection: local

    monitoring:
      hosts:
        monitor01:
          ansible_host: 10.4.10.40
          ansible_user: henrik

    linux:
      children:
        automation:
        monitoring:
