all:
  children:

    automation:
      hosts:
        automation01:
          ansible_connection: local

    monitoring:
      hosts:
        monitor01:
          ansible_host: 10.4.10.40

    management:
      hosts:
        pdm01:
          ansible_host: 10.4.10.45

        pdm02:
          ansible_host: 10.4.10.46

        pegaprox01:
          ansible_host: 10.4.10.47

    platform:
      hosts:
        platform01:
          ansible_host: 10.4.10.99

    backup:
      hosts:
        pbs01:
          ansible_host: 10.4.10.15
          ansible_user: root

    infrastructure_linux:
      hosts:
        ubuntu-server:
          ansible_host: 10.4.10.22

    infrastructure_windows:
      hosts:
        win2025srv:
          ansible_host: 10.4.10.20

        win2025srv2:
          ansible_host: 10.4.10.21

    linux:
      children:
        automation:
        monitoring:
        management:
        platform:
        backup:
        infrastructure_linux:

    windows:
      children:
        infrastructure_windows:
