all:
  children:
    automation:
      hosts:
        automation01:
          ansible_connection: local

    monitoring:
      hosts:
        monitor01:
          ansible_host: 10.4.10.40

    management:
      hosts:
        pegaprox01:
          ansible_host: 10.4.10.47

    platform:
      hosts:
        platform01:
          ansible_host: 10.4.10.99

    linux:
      children:
        automation:
        monitoring:
        management:
        platform:
