server {
    listen 443 ssl http2;

    server_name forgejo.gruppe4.local;

    ssl_certificate     /etc/nginx/certs/forgejo.gruppe4.local.crt;
    ssl_certificate_key /etc/nginx/certs/forgejo.gruppe4.local.key;

    client_max_body_size 500M;

    location / {
        proxy_pass http://host.docker.internal:3000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
