server {
    listen 443 ssl;

    server_name portainer.gruppe4.local;

    ssl_certificate     /etc/nginx/certs/portainer.gruppe4.local.crt;
    ssl_certificate_key /etc/nginx/certs/portainer.gruppe4.local.key;

    client_max_body_size 500M;

    location / {
        proxy_pass https://host.docker.internal:9443;

        proxy_ssl_verify off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
