---
common_packages:
  - qemu-guest-agent
  - curl
  - wget
  - git
  - vim
  - htop
  - tree
  - net-tools
  - dnsutils
  - unzip
  - python3-pip

github_ssh_users:
  - it-supporter

ssh_authorized_users:
  - henrik
  - root
