all:
  vars:
    ansible_user: henrik

  children:

    k3s_servers:
      hosts:
        k3s01:
          ansible_host: 10.4.10.60
        k3s02:
          ansible_host: 10.4.10.61
        k3s03:
          ansible_host: 10.4.10.62
