all:
  vars:
    ansible_user: henrik

  children:

    students:
      hosts:
        student01:
          ansible_host: 10.4.10.200
          pair_id: 1
          pair_name: pair01
          cyberrange_role: student
          partner_ip: 10.4.10.201
        student02:
          ansible_host: 10.4.10.202
          pair_id: 2
          pair_name: pair02
          cyberrange_role: student
          partner_ip: 10.4.10.203

    targets:
      hosts:
        target01:
          ansible_host: 10.4.10.201
          pair_id: 1
          pair_name: pair01
          cyberrange_role: target
          partner_ip: 10.4.10.200
        target02:
          ansible_host: 10.4.10.203
          pair_id: 2
          pair_name: pair02
          cyberrange_role: target
          partner_ip: 10.4.10.202
