---
- name: Install baseline packages
  ansible.builtin.apt:
    name: "{{ baseline_packages }}"
    state: present
    update_cache: true

- name: Install baseline services
  ansible.builtin.apt:
    name: "{{ baseline_services }}"
    state: present

- name: Enable baseline services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ baseline_services }}"
