---
- name: Add Grafana Helm repository
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts

- name: Install Loki
  kubernetes.core.helm:
    name: loki
    chart_ref: grafana/loki
    release_namespace: monitoring
    create_namespace: true
    wait: true

    values:

      deploymentMode: SingleBinary

      loki:
        auth_enabled: false

        commonConfig:
          replication_factor: 1

        storage:
          type: filesystem

      singleBinary:
        replicas: 1

      backend:
        replicas: 0

      read:
        replicas: 0

      write:
        replicas: 0

      chunksCache:
        enabled: false

      resultsCache:
        enabled: false

      gateway:
        enabled: false
