- Monitoring:
    - Grafana:
        icon: grafana.png
        href: http://10.4.10.40:4000
        siteMonitor: http://10.4.10.40:4000

    - Prometheus:
        icon: prometheus.png
        href: http://10.4.10.40:4010
        siteMonitor: http://10.4.10.40:4010

    - Homepage:
        icon: homepage.png
        href: http://10.4.10.40:4040
        siteMonitor: http://10.4.10.40:4040

    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://10.4.10.40:4030
        siteMonitor: http://10.4.10.40:4030

- Virtualization:
    - Proxmox Virtual Environment S10:
        icon: proxmox.png
        href: https://10.4.10.10:8006
        siteMonitor: https://10.4.10.10:8006

    - Proxmox Virtual Environment S11:
        icon: proxmox.png
        href: https://10.4.10.11:8006
        siteMonitor: https://10.4.10.11:8006

    - Proxmox Virtual Environment S12:
        icon: proxmox.png
        href: https://10.4.10.12:8006
        siteMonitor: https://10.4.10.12:8006

- Management:
    - Proxmox Datacenter Manager:
        icon: proxmox-light.png
        href: https://10.4.10.45:8443
        siteMonitor: https://10.4.10.45:8443

    - Proxmox Datacenter Manager 2:
        icon: proxmox-light.png
        href: https://10.4.10.46:8443
        siteMonitor: https://10.4.10.46:8443

    - PegaProx:
        icon: sh-pegaprox
        href: https://10.4.10.47:5000
        siteMonitor: https://10.4.10.47:5000

- Security:
    - OpnSense Firewall :
        icon: opnsense.png
        href: https://10.4.10.2
        siteMonitor: https://10.4.10.2

    - OpnSense Firewall 2:
        icon: opnsense.png
        href: https://10.4.10.3
        siteMonitor: https://10.4.10.3

- Infrastructure:
    - Monitoring Server:
        icon: sh-ubuntu
        href: http://10.4.10.40
        siteMonitor: https://10.4.10.47:5000

    - Windows 2025 Server:
        icon: microsoft-windows.svg
        href: http://10.4.10.20
        siteMonitor: https://10.4.10.20

    - CARP Virtual Gateway:
        icon: sh-pufferfish-host
        href: https://10.4.10.1
        siteMonitor: https://10.4.10.1

